---
title: "Credit Decision Trees"
author: "Caroline Bower"
date: "4/7/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r bibliotecca}
credit <- read.csv("credit.csv")
RNGversion("3.5.2"); set.seed(123)

library("C50")
library("gmodels")
```

```{r functionland}

```

```{r model}
# from seed pull random lines from file
train_sample <- sample(1000, 900)

# change default to factor
credit$default <- as.factor(credit$default)

# create train and test sets
credit_tr <- credit[train_sample, ]
credit_te <- credit[-train_sample, ]

prop.table(table(credit_tr$default))
prop.table(table(credit_te$default))

credit_model <- C5.0(credit_tr[-17], credit_tr$default)
```

```{r confusion matrix}
summary(credit_model)
```

```{r predicting}
credit_pred <- predict(credit_model, credit_te)
CrossTable(credit_te$default, credit_pred,
           prop.chisq = FALSE, prop.c = FALSE, prop.r = FALSE,
           dnn = c('actual default', 'predicted default'))
```

```{r boost}
credit_boost10 <- C5.0(credit_tr[-17], credit_tr$default, 
                       trials = 10)
summary(credit_boost10)
```

```{r boost results}
credit_boost_pred10 <- predict(credit_boost10, credit_te)
CrossTable(credit_te$default, credit_boost_pred10,
           prop.chisq = FALSE, prop.c = FALSE, prop.r = FALSE,
           dnn = c('actual default', 'predicted default'))
```

```{r Keanu Reeves}
matrix_dimensions <- list(c("no", "yes"), c("no", "yes"))
names(matrix_dimensions) <- c("predicted", "actual")

error_cost <- matrix(c(0, 1, 4, 0), nrow = 2,
                     dimnames = matrix_dimensions)
credit_cost <- C5.0(credit_tr[-17], credit_tr$default,
                    costs = error_cost)
credit_cost_pred <- predict(credit_cost, credit_te)
CrossTable(credit_te$default, credit_cost_pred,
           prop.chisq = FALSE, prop.c = FALSE, prop.r = FALSE,
           dnn = c('actual default', 'predicted default'))
```
